<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0;net8.0</TargetFrameworks>
    <Version>1.1.1</Version>

    <Title>Makes memory addresses visible in C#.</Title>
    <PackageReadmeFile>README.md</PackageReadmeFile>

    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>

    <RepositoryUrl>https://github.com/mnemonic-bit/AddressHelpers.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>

    <Authors>Marco Ruether</Authors>
    <Copyright>Marco Ruether</Copyright>
    <PackageReadmeFile>README.md</PackageReadmeFile>

    <AssemblyName>MemoryAddressHelpers</AssemblyName>
    <RootNamespace>MemoryAddressHelpers</RootNamespace>
    <Nullable>enable</Nullable>

    <PackageId>MemoryAddressHelpers</PackageId>
    <Description>This library provides helpers to show the actual address of an instance.</Description>
    <PackageTags>Memroy, Address</PackageTags>
    <IsPackable>true</IsPackable>

    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DevelopmentDependency>true</DevelopmentDependency>
  </PropertyGroup>

  <ItemGroup>
    <None Include=".\README.md" Pack="true" PackagePath="." />
  </ItemGroup>

  <ItemGroup>
    <None Update="README.md">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
